- name: Parse Gnome Shell version
  shell: |
    set -o pipefail
    gnome-shell --version | sed 's/[^0-9.]*\([0-9.]*\).*/\1/'
  register: gnome_shell_version
  changed_when: no

- name: Get Gnome Shell extension info
  uri:
    url: "https://extensions.gnome.org/extension-info/?pk={{ item }}&shell_version={{ gnome_shell_version.stdout }}"
    return_content: yes
  loop: "{{ gnome_extension_ids }}"
  register: r_gnome_extension_info

- name: Install extensions
  include_tasks: install_extension.yml
  vars:
    gnome_extension_info: "{{ item.json }}"
  loop: "{{ r_gnome_extension_info.results }}"
